FROM alpine AS build
ARG TARGETPLATFORM
WORKDIR build
COPY dist/ dist/
RUN apk --no-cache add ca-certificates jq && \
    TARGETPLATFORM="${TARGETPLATFORM//\//_}" && \
    TARGETPLATFORM="${TARGETPLATFORM//v/}" && \
    mkdir /prod && \
    for file in mv $(jq -r --arg TP ${TARGETPLATFORM} '.[]|select(has("target"))|select(.target | startswith($TP)).path' dist/artifacts.json); do mv "$file" /prod/; done;
RUN rm -rf /build
WORKDIR /run
ENTRYPOINT ["/prod/docker-lock"]

